"""
Monthly digest generation. Alexandria synthesises the state of the art across
all topics in the project, highlighting significant developments and gaps.
"""
from datetime import datetime, timezone
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.models.project import Project, Digest
from app.models.reference import Reference
from app.services.llm import complete_text


async def generate_digest(
    db: AsyncSession,
    project_id: int,
    user_id: int,
    period_start: datetime,
    period_end: datetime,
    model: str = "claude-sonnet-4-6",
) -> Digest:
    project_result = await db.execute(select(Project).where(Project.id == project_id))
    project = project_result.scalar_one_or_none()
    if not project:
        raise ValueError(f"Project {project_id} not found")

    new_refs_result = await db.execute(
        select(Reference)
        .options(selectinload(Reference.tags))
        .where(
            Reference.project_id == project_id,
            Reference.created_at >= period_start,
            Reference.created_at <= period_end,
        )
        .order_by(Reference.created_at.desc())
    )
    new_refs = new_refs_result.scalars().all()

    all_refs_result = await db.execute(
        select(Reference)
        .options(selectinload(Reference.tags))
        .where(Reference.project_id == project_id)
        .order_by(Reference.created_at.desc())
        .limit(100)
    )
    all_refs = all_refs_result.scalars().all()

    new_refs_data = [
        {
            "title": r.title,
            "authors": r.authors,
            "year": r.year,
            "source_type": r.source_type,
            "summary": (r.summary or r.abstract or "")[:200],
            "tags": [t.tag for t in r.tags],
        }
        for r in new_refs
    ]

    all_tags: dict[str, int] = {}
    for r in all_refs:
        for t in r.tags:
            all_tags[t.tag] = all_tags.get(t.tag, 0) + 1
    top_topics = sorted(all_tags.items(), key=lambda x: -x[1])[:15]

    prompt = f"""You are Alexandria, the research librarian for "{project.name}".

Project: {project.description}
Period: {period_start.strftime('%B %Y')} to {period_end.strftime('%B %Y')}

New references added this period ({len(new_refs)} total):
{_format_refs(new_refs_data)}

Top topics across the full library: {', '.join(f"{t}({c})" for t, c in top_topics)}

Generate a comprehensive monthly digest in Markdown:

# Alexandria Monthly Digest — {period_end.strftime('%B %Y')}
## {project.name}

### Executive Summary
### New Additions This Period
### State of the Art — Key Topics
### Notable Developments
### Coverage Gaps
### Recommended Next Steps

---
*Generated by Alexandria on {datetime.now(timezone.utc).strftime('%Y-%m-%d')}*"""

    content = await complete_text(model, prompt, max_tokens=3000)

    digest = Digest(
        project_id=project_id,
        title=f"Monthly Digest — {period_end.strftime('%B %Y')}",
        content=content,
        period_start=period_start,
        period_end=period_end,
        new_references=len(new_refs),
        created_by=user_id,
    )
    db.add(digest)
    await db.flush()
    await db.refresh(digest)
    return digest


def _format_refs(refs: list[dict]) -> str:
    if not refs:
        return "(none)"
    lines = []
    for r in refs[:30]:
        lines.append(f"- {r['title']} ({r.get('year', 'n.d.')}) [{r['source_type']}]")
        if r.get("summary"):
            lines.append(f"  {r['summary'][:180]}")
    return "\n".join(lines)
